### ISSUE TITLE
reimplement room_to_displaay_x / y

### ISSUE THREAD

**Issue by jack27121** [jack27121/STANNcam#32] opened 2023-11-07 22:40 UTC
it's in the stanncam code it's just uncommented

this might work, but haven't tested it

```
	/// @function room_to_display_x
	/// @description returns the room x position as the position on the display relative to camera
	/// @param {Real} x_
	/// @returns {Real}
	/// @ignore
	static room_to_display_x = function(x_){
		return ((x_-get_y()-x_frac) / get_zoom_x()) * stanncam_get_res_scale_x();
	}
```

**Comment by bfrymire** [comment] 2024-01-17 03:23
Duplicate of #51

**Comment by bfrymire** [comment] 2024-01-17 03:24
Duplicate of #51

**Closed by bfrymire** 2024-01-17 03:24 UTC
Labels: feature suggestion
